FROM oven/bun:1-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock
COPY ./packages ./packages
COPY ./apps/web/package.json ./apps/web/package.json


RUN bun install
COPY . .

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN bun run db:generate
RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]